server {
        listen 80;
        listen [::]:80;

        server_name your-domain.com; # replace with your domain

        root /var/www/html/blog;
        index index.html;

        gzip on;
        gzip_min_length 1024; # over 1KB
        gzip_comp_level 5;
        gzip_vary on;
        gzip_disable "msie6"; # except old IE

        gzip_types
            text/plain
            text/css
            application/json
            application/javascript
            text/javascript
            application/x-javascript
            text/xml
            application/xml
            application/xml+rss
            image/svg+xml;

        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
                expires 1d;
                add_header Cache-Control "public, no-transform";
        }

        location = /index.html {
            # prevent caching index.html (if cached, the app will not update)
                add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
        }

        location / { # for vue router
                try_files $uri $uri/ /index.html;
        }

        location /api { # backend API
        proxy_pass http://localhost:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        client_max_body_size 128M; # for uploading
        }
}
